# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and test feature branch

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: pull and checkout from git repository
      run: |
        echo "pulling and checking out from git repository"
    - uses: actions/setup-java@v6
      with:
        distribution: 'temurin' #See 'Supported distributions' for available options
        java-version: '17'

    - name: build with maven
      run: |
        mvn clean install
        echo "build with maven"
